version: 2.1

executors:
    grid2op-executor:
        docker:
            - image: bdonnot/grid2op:test
        working_directory: /Grid2Op
    python36:
        docker:
            - image: python:3.6-slim-buster
    python37:
        docker:
            - image: python:3.7-slim-buster
    python38:
        docker:
            - image: python:3.8-slim-buster
    python39:
        docker:
            - image: python:3.9-slim-buster

jobs:
    test:
        executor: grid2op-executor
        parallelism: 4
        steps:
            - checkout
            - run:
                command: |
                  cd grid2op/tests/
                  python3 helper_list_test.py | circleci tests split > /tmp/tests_run
                  python3 -m unittest $(cat /tmp/tests_run)
    install36:
        executor: python36
        steps:
            - checkout
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
                command: |
                    source venv_test/bin/activate
                    pip install -U numba
                    pip install -U "numpy>=1.18,<1.19"
                    pip install -U .[test]
                    grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U "numpy>=1.19,<1.20"
                   pip install -U .[test]
                   grid2op.testinstall
    install37:
        executor: python37
        steps:
            - checkout
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
                command: |
                    source venv_test/bin/activate
                    pip install -U numba
                    pip install -U "numpy>=1.18,<1.19"
                    pip install -U .[test]
                    grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U "numpy>=1.19,<1.20"
                   pip install -U .[test]
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U "numpy>=1.20,<1.21"
                   pip install -U .[test]
                   grid2op.testinstall
    install38:
        executor: python38
        steps:
            - checkout
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
                command: |
                    source venv_test/bin/activate
                    pip install -U numba
                    pip install -U "numpy>=1.18,<1.19"
                    pip install -U .[test]
                    grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U "numpy>=1.19,<1.20"
                   pip install -U .[test]
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U "numpy>=1.20,<1.21"
                   pip install -U .[test]
                   grid2op.testinstall
    install39:
        executor: python39
        steps:
            - checkout
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U "numpy>=1.19,<1.20"
                   pip install -U .[test]
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U "numpy>=1.20,<1.21"
                   pip install -U .[test]
                   grid2op.testinstall

workflows:
    version: 2.1
    test:
        jobs:
          - test
    install:
        jobs:
          - install36
          - install37
          - install38
          - install39
